"""IML Protocol v2 — Constants and limits."""

PROTOCOL_VERSION = "2.0"

# Identifier constraints
ACTION_ID_MAX_LEN = 64
PLAN_ID_MAX_LEN = 128
MODULE_ID_MAX_LEN = 64
ACTION_NAME_MAX_LEN = 64
LABEL_MAX_LEN = 256

# Plan limits
MAX_ACTIONS_PER_PLAN = 500
MAX_PLAN_DESCRIPTION_LEN = 1024
MAX_TAGS_PER_ACTION = 20
MAX_TAG_LEN = 64

# Execution limits
DEFAULT_ACTION_TIMEOUT_SECONDS = 60
MAX_ACTION_TIMEOUT_SECONDS = 3600
MIN_ACTION_TIMEOUT_SECONDS = 1

# Retry limits
DEFAULT_RETRY_MAX_ATTEMPTS = 3
MAX_RETRY_MAX_ATTEMPTS = 10
DEFAULT_RETRY_DELAY_SECONDS = 1.0
MAX_RETRY_DELAY_SECONDS = 300.0
DEFAULT_RETRY_BACKOFF_FACTOR = 2.0

# Template syntax
TEMPLATE_OPEN = "{{"
TEMPLATE_CLOSE = "}}"
TEMPLATE_PREFIX_RESULT = "result"
TEMPLATE_PREFIX_MEMORY = "memory"
TEMPLATE_PREFIX_ENV = "env"

# Perception
DEFAULT_PERCEPTION_TIMEOUT_SECONDS = 5
MAX_PERCEPTION_TIMEOUT_SECONDS = 60

# Memory
DEFAULT_MEMORY_TOP_K = 3
MAX_MEMORY_TOP_K = 20

# Header for API requests
HEADER_API_TOKEN = "X-LLMOS-Token"
HEADER_SESSION_ID = "X-LLMOS-Session"
HEADER_PLAN_ID = "X-LLMOS-Plan"
